name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - h5py
  - statsmodels
  - seaborn
  - networkx
  - igraph
  - anndata
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - pip
  - pip:
    - scikit-learn
    - numpy
